basePath: /
consumes:
    - application/json
definitions:
    DataTemplateColumnDTO:
        description: DataTemplateColumnDTO represents a column of a DT
        x-go-package: excalibur/internal/handler/dto
    DataTemplateDTO:
        description: DataTemplateDTO represents the a data template structure
        x-go-package: excalibur/internal/handler/dto
info:
    description: Documentation for Excalibur API
    title: entrypoint to the API
    version: 1.0.0
paths:
    /datatemplate:
        get:
            description: Return a list of all datatemplates from the database
            operationId: listDataTemplates
            responses:
                "200":
                    $ref: '#/responses/dataTemplateListResponse'
            tags:
                - datatemplate
        post:
            description: Create a new datatemplate
            operationId: createDataTemplate
            parameters:
                - in: query
                  name: Body
            responses:
                "200":
                    $ref: '#/responses/dataTemplateResponse'
            tags:
                - datatemplate
    /datatemplate/{id}:
        get:
            description: Gets a DataTemplate by the specified ID
            operationId: getDataTemplateByID
            parameters:
                - description: The ID of the datatemplate
                  in: path
                  name: id
                  required: true
                  type: string
                  x-go-name: ID
            responses:
                "200":
                    $ref: '#/responses/dataTemplateResponse'
            tags:
                - datatemplate
        post:
            description: Delete the datatemplate associated with the given ID
            operationId: deleteDataTemplate
            responses:
                "200":
                    $ref: '#/responses/dataTemplateResponse'
            tags:
                - datatemplate
        put:
            description: Update a products details
            operationId: updateDataTemplate
            parameters:
                - description: The ID of the datatemplate
                  in: path
                  name: id
                  required: true
                  type: string
                  x-go-name: ID
            responses:
                "200":
                    $ref: '#/responses/hateoasWithIdResponse'
            tags:
                - datatemplate
produces:
    - application/json
responses:
    dataTemplateListResponse:
        description: A list of DataTemplate objects
        schema:
            items: {}
            type: array
    dataTemplateResponse:
        description: Data structure representing a single DataTemplate
    hateoasWithIdResponse:
        description: A response detailing the ID of the affected object, with appropriate Hateoas links
schemes:
    - http
swagger: "2.0"
